version: 2.1

orbs:
  node: circleci/node@2.1.1

workflow_filters: &filters
  filters:
    branches:
      ignore:
      - docs

workflows:
  test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version: ["10.20", "12.17", "14.3"]
          version: << matrix.version >>
          pkg-manager: yarn
          run-command:
              yarn test -p cli,cli-service,cli-shared-utils
